In [1]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:


arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print(arr.ndim)


2nd element on 1st row:  2
2


In [7]:
ar=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(ar)
print(type(ar))
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
2


In [10]:
print(ar[0,1,2])
print(ar[0,1])

6
[4 5 6]


In [12]:
ar = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(ar[1,4])

10


In [3]:
import numpy as np
ar = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(ar[1, 1:4])

[7 8 9]


In [2]:
import numpy as np
arr = np.array([1,5,8,3,6,22,8,7,7])
x=arr.copy()
arr[0]=42
print(arr)
print(x)                                      #copying the array
            #copy cannot be updated by updating the array(original)

[42  5  8  3  6 22  8  7  7]
[ 1  5  8  3  6 22  8  7  7]


In [4]:
x=arr.view()       #creating view for an arry
                    #view can be updated by updating the array(original)
arr[1]=42
print(arr)
print(x)

[42 42  8  3  6 22  8  7  7]
[42 42  8  3  6 22  8  7  7]


In [5]:
x[0]=40
print(arr)
print(x)

[40 42  8  3  6 22  8  7  7]
[40 42  8  3  6 22  8  7  7]


In [6]:

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[40 42  8  3  6 22  8  7  7]


In [7]:
print(arr.shape)

(9,)


In [12]:
k=arr.reshape(3,3)
print(k)

[[40 42  8]
 [ 3  6 22]
 [ 8  7  7]]
